[build]
  publish = "public"
  functions = "netlify/functions"
  command = "node public/generate-pages.js"

[functions]
  included_files = ["netlify/functions/tattoo_shops.json"]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

