[build]
publish = "public"
command = "npm install"

[functions]
directory = "functions"
node_bundler = "esbuild"

# Environment variables for production
[build.environment]
NODE_VERSION = "18"

# API redirects to static JSON files
[[redirects]]
from = "/api/parlors/random"
to = "/api/parlors/random.json"
status = 200

[[redirects]]
from = "/api/parlors/featured"
to = "/api/parlors/featured.json"
status = 200

[[redirects]]
from = "/api/parlors/states"
to = "/api/parlors/states.json"
status = 200

[[redirects]]
from = "/api/parlors"
to = "/api/parlors.json"
status = 200

[[redirects]]
from = "/api/artists"
to = "/api/artists.json"
status = 200

# SPA fallback for client-side routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Headers for better performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000"