[build]
  command = "chmod +x ./build.sh && ./build.sh"
  publish = "public"

[functions]
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/parlors/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# This empty plugins section disables auto-detection
[plugins]

# Disable asset optimization and processing
[build.processing]
  skip_processing = true