[build]
  publish = "public"
  functions = "netlify/functions"
  command = "node public/generate-pages.js"

[functions]
  included_files = ["netlify/functions/tattoo_shops.json"]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

[[redirects]]
  from = "https://inkmasterlink.com/*"
  to = "https://www.inkmasterlink.com/:splat"
  status = 301
  force = true
