[build]
publish = "public"
command = "exit 0"

[functions]
directory = "functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/parlors/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200