[build]
  publish = "public"
  functions = "netlify/functions"
  command = "node public/generate-pages.js"

[functions]
  included_files = ["netlify/functions/tattoo_shops.json"]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "https://inkmasterlink.com/*"
  to = "https://www.inkmasterlink.com/:splat"
  status = 301
  force = true

[[headers]]
for = "/*"
  [headers.values]
  X-Robots-Tag = "all"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
  Cache-Control = "no-cache"

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true
