[build]
publish = "public"
command = "npm install"

[functions]
directory = "functions"
node_bundler = "esbuild"

# Plugin to automatically install function dependencies
[[plugins]]
package = "@netlify/plugin-functions-install-core"

# Environment variables for production
[build.environment]
NODE_VERSION = "18"

# API redirects
[[redirects]]
from = "/api/parlors/*"
to = "/.netlify/functions/parlors/:splat"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/parlors"
status = 200

# SPA fallback for client-side routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Headers for better performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000"